### ISSUE TITLE
GTK vertical slider control track is using gray instead of alpha

### ISSUE THREAD

**Issue by willco007** [elementary/stylesheet#1086]
## What Happened
In a GTK 3 application the vertical slider control track, bottom end is using gray pixel colors instead of alpha. (see screenshot)

## Expected Behavior
The track should be using black with alpha so it blends with dark backgrounds correctly

## Steps to Reproduce

1. Run the GTK test app or another app that uses the vertical slider control

### Logs
N/A

## Platform Information
6.0 Oden currently up to date

<img width="273" alt="slider_track" src="https://user-images.githubusercontent.com/4294739/132064049-b3a45a5d-6c6e-4343-9269-7f6190e64dc2.png">

**Comment by danrabbit** [comment]
Hey Will, thanks for the report! It looks like this app or at least this section of the app should probably request the dark version of the stylesheet so that the widgets use dark styles. We've got some docs here about how to set the dark style for your whole app: https://docs.elementary.io/develop/apis/color-scheme#setting-a-dark-style

If you just want a certain widget in your app to use the dark style, you can do that by creating a Gtk.CssProvider with the dark style and then applying it to the widget's style context like this:

```
var dark_css_provider = Gtk.CssProvider.get_named (Gtk.Settings.get_default ().gtk_theme_name, "dark");

my_widget.get_style_context ().add_provider (dark_css_provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION);
```

**Comment by willco007** [comment]
_Yeah_, it 100% should be...the issue is this code is cross platform and so it complicates things a bit (GTK is abstracted away by the toolkit) and the appearance is the same on Windows. I'll poke at it and see if I can make it use the native dark theme.

**Comment by cassidyjames** [comment]
@willco007 are you bundling the stylesheet with this app, or will it use whatever the OS/desktop it's running on is using? If you're bundling it, you may be able to guarantee the style by setting `io.elementary.stylesheet.banana:dark` in your tooling. Otherwise yeah, you'll need to see if your tooling supports requesting the dark theme variant in GTK.

**Comment by willco007** [comment]
It's using whatever the OS is providing; which is nice for integration, but not so nice for colors on the dark background.

**Comment by cassidyjames** [comment]
@willco007 ha yeah, in that case you could either not set the dark background (and let the GTK styles provide a background), and/or see if you can request the dark variant to get a better shot at contrast. The latter would also help with things like the text entry and checkboxes being styled to be on a dark background as well.

I _think_ this issue is out of scope for this repo, but I'd be happy to see how I can help any further with this over DM, since I know what project you're working on. :stuck_out_tongue_closed_eyes:
