### ISSUE TITLE
SettingsSidebar corner is not rounded when placed in Popover

### ISSUE THREAD

**Issue by stsdc** [elementary/stylesheet#1100]
### What Happened?

![image](https://user-images.githubusercontent.com/6031763/141702421-9fbeed69-8a31-4b3b-9f84-de00435876b4.png)

Also this might be a GTK3 with Popover issue, not sure.

### Steps to Reproduce

Place SettingsView inside a Gtk.Popover

### Expected Behavior

Expected whatever is placed inside a Popover to have rounded corners.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![image](https://user-images.githubusercontent.com/6031763/141702549-49b105f2-6665-49a2-b65d-47760eda4a35.png)

**Comment by danrabbit** [comment]
Gonna move this to the stylesheet because it would need to be solved there since GTK 3 doesn’t mask the corners of widgets to their container

My first thoughts are this is probably a case where you should use a dialog instead of a popover. Popovers should really be used for super quick interactions. If you need a complex widget like settings sidebar, the user is probably spending enough time there that it warrants a less ephemeral piece of UI

**Comment by danrabbit** [comment]
I'm gonna go ahead and close this since there's not really a way to solve this in GTK3. Your best bet would be to use some custom CSS to pad the popover a bit. In GTK4 widgets can actually clip their children, so that's the proper fix
