### ISSUE TITLE
Window design request

### ISSUE THREAD

**Issue by nojo99** [elementary/stylesheet#1203]
### Problem

On the RasPi 400 beta version;

I would like the menu bar to have a button to shrink the window down to the dock.  Clicking on the dock icon works but is not intuitive for users coming from another window system.  Another request is to make scroll bars wider to start with, I like that they expand and the size when expanded, if the app expands the bar at all, like this github page,  The mouse pointer can be tricky to get onto the narrow bar to start.  For some reason  Linux systems have always had trouble with getting the mouse pointer to recognize the edge of a window border, not so with BSD/Mac/Win mouse drivers.

The stock web browser Epiphany (?) in dark mode the background becomes the foreground too, the page content looks blank but it isn't, like black text on a black background or white text on a white background.  Not a problem with Firefox though.

### Proposal

Proposal is included in the Problem description.

Eos is looking very promising for RasPi users.  Would be nice if it would install using the PiNN multi-boot partitioning system, unique to the RasPi.   And, how about a upgrade to Ubuntu 21.???.

**Comment by danrabbit** [comment]
Hey thanks for your feedback! Unfortunately we're not able to track lots of grouped feedback like this. Each separate issue and feature request should be its own report so that we can assign people, track in projects, discuss solutions, and close issues when they're resolved.

As is, I'm going to close this issue since it can't be tracked and describes multiple issues and feature requests that would need to be assigned to multiple different repos
