### ISSUE TITLE
GTK 4 apps like gtk4-widget-factory dont respect the EOS 7 dark theme

### ISSUE THREAD

**Issue by BAProductions** [elementary/stylesheet#1243]
### What Happened?

<img width="1216" alt="Screenshot 2023-02-23 at 11 37 27 AM" src="https://user-images.githubusercontent.com/2386630/220971888-8f15bfc9-be57-48d4-8a6a-ebc0bcae6f1b.png">

### Steps to Reproduce

opened gtk4-widget-factory
& it open with the light theme

### Expected Behavior

opened gtk4-widget-factory
& it open with the dark theme

### OS Version

7.x (Horus)

### Software Version

Compiled from git

### Log Output

```shell
NONE
```

### Hardware Info

It's a VM

**Comment by danirabbit** [comment]
Thanks for your report! Apps need to opt-in to the freedesktop dark style preference to use it, so you'll need to file issue reports against apps that aren't behaving as you expect. This is a cross-platform standard that's being adopted by all of the major desktops.

Closing as "Out of scope" since it's up to apps to opt-in to the dark style preference
