### ISSUE TITLE
Buttons don't play well with text scaling. 

### ISSUE THREAD

**Issue by tnetenbaa** [elementary/stylesheet#1294]
### What Happened?

When scaling text below 1.00 in settings, everything but buttons with text seem to scale appropriately. For example, I have scaling set to 0.80, and the buttons have a huge gap below the text.
![Screenshot from 2024-05-26 04 39 38](https://github.com/elementary/triage/assets/158774339/10eb6276-9e12-4668-9c59-33effb72d277)

### Steps to Reproduce

Open something that has a multi-choice dialog (ex. "Run as Administrator" with Files)

### Expected Behavior

Buttons scale correctly.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Looks like this was an issue with Gtk.ButtonBox which no longer exists in GTK 4:

![Screenshot from 2024-05-27 08 22 56](https://github.com/elementary/stylesheet/assets/7277719/d6c4eaa1-5182-447c-97c2-337456603438)

Closing as "Out of scope" since it's with a removed upstream component and anything migrated to GTK 4 won't experience this issue

**Comment by tnetenbaa** [comment]
Is there any ETA on when this fix will hit Files? Even in the latest daily for OS 8, the issue is still present.
![Screenshot from 2024-05-27 17 28 07](https://github.com/elementary/stylesheet/assets/158774339/295e481d-5d01-40ae-a819-5838b518bd1e)

**Comment by danirabbit** [comment]
@tnetenbaa there's some work in progress to port files to GTK 4, but I can't say it looks like it will be finished imminently. There's no way to give an estimation on how long it will take. It just depends on time available from contributors
