### ISSUE TITLE
(New Feature) Make the wingpanel black opaque When something is in fullscreen mode.  

### ISSUE THREAD

**Issue by Blast-City** [elementary/stylesheet#241]
Hi.  

I posted this issue on the Gala section, but i think i should post it here instead.  

On the theme gtk file there is an option that makes the wingpanel opaque when a window is maximized.   I think this should be also the case when something is in fullscreen mode.  

Imagine the following situation:

- You have a light wallpaper so the wingpanel is transparent with black letters and icons.  

- Open a fullscreen terminal.  

- If you open a files window in the foreground, you cannot see the information in the wingpanel since it's black and the terminal is also black.  

I think it would be nice if when a window is in fullscreen, the wingpanel would have a black background with white letters and icons (like when a window is maximized) so that you can see the information in the wingpanel when something is in foreground.

**Comment by grinningtadpole** [comment]
I would argue that the wingpanel and dock should remain hidden on a workspace as long as an application is in full screen mode. 

Right now, when I run GIMP in full screen mode, the panel and dock remain hidden as long as the primary window has focus. This is good behavior. I put the application in full screen mode to gain the extra real estate at the top of the screen and to avoid fighting the dock when I change zoom levels at bottom of the GIMP window. If I want access to the wingpanel or dock, I can either take GIMP out of full screen mode or switch to a neighboring workspace (even easier if you enable the corner actions).

Currently, however, the moment any GIMP tool palette gains focus (separate window), the opaque wingpanel appears and the dock becomes active. This is not only distracting (wingpanel constantly appears and disappears) it is also a PITA for working on large images. If I change brushes, tools, colors, etc. (i.e. palette gains focus) and then decide I want to zoom to a different level, I have to click back in the main image window before doing so. Otherwise the wingpanel hides the GIMP top menu or the dock fights for control when accessing the controls on the bottom of the GIMP panel.

There is a reason we turn full-screen mode on in apps. It is to gain as much screen real estate as possible and to focus only on that one task. The UI should respect this and get out of the way.

**Comment by Astro-City** [comment]
Hi.  

That would be even better.

**Comment by Blast-City** [comment]
Please Close this issue.

I tested this on Juno and the solution given by grinningtadpole seems to be present.

Thanks.

**Comment by Blast-City** [comment]
Thanks btkostner.
