### ISSUE TITLE
 Default dock background color doesn't make it clear that the Files app is open

### ISSUE THREAD

**Issue by uncertainquark** [elementary/stylesheet#323]
Check screenshot with default white plank:
![screenshot from 2018-03-24 17-04-47](https://user-images.githubusercontent.com/22585732/37863543-918f10a8-2f85-11e8-882a-af8b354de74f.png)

And now a dark plank:
![screenshot from 2018-03-24 17-04-38](https://user-images.githubusercontent.com/22585732/37863545-98623e3c-2f85-11e8-814a-4a569e421ca1.png)

It is only clear in the dark plank that the Files app is open and not visually distinguished on the white dock.

The reverse is true for the terminal app.
![screenshot from 2018-03-24 17-06-08](https://user-images.githubusercontent.com/22585732/37863559-cdd73cf2-2f85-11e8-8099-843757bc1d9d.png)
![screenshot from 2018-03-24 17-07-19](https://user-images.githubusercontent.com/22585732/37863560-d3d9f5f4-2f85-11e8-90c7-0f08bd2e214b.png)

Considering the Issue #322, it might be a good idea to do some minor changes to the way open applications are visually conveyed on the dock.

**Comment by cassidyjames** [comment]
I don't think this is controllable with the stylesheet since there's not a large amount of styling we can do—and as you pointed out, doing something drastic like switching to a dark dock would just cause the same issue with other apps.

Instead, this would be an issue with [Plank](https://launchpad.net/plank).
