### ISSUE TITLE
Change plank color depending on the wallpaper too and not just panel color

### ISSUE THREAD

**Issue by uncertainquark** [elementary/stylesheet#324]
In the [recent elementary blog post](https://medium.com/elementaryos/juno-progress-for-january-february-9b276042716e), it was detailed how the panel will change colors to better suit the wallpaper. The same should be done for the plank dock too (light or dark) for consistency if nothing else.

To give an example of how ugly the white dock can look on a dark wallpaper, see here:

![screenshot from 2018-03-24 16-15-17](https://user-images.githubusercontent.com/22585732/37863119-a3950bb0-2f7e-11e8-83e5-00c42fd8edf0.png)

And here's the same wallpaper on a dark plank dock:

![screenshot from 2018-03-24 16-15-05](https://user-images.githubusercontent.com/22585732/37863126-b50ab840-2f7e-11e8-8dd8-e2f57432ad97.png)

**Comment by micahilbery** [comment]
The panel and dock are functionally different. I think the dock is more of an active thing as a place for favorite and currently running apps where the panel is more passive system information. So I don't think they necessarily should be consistent with each other. Anyone else in @elementary/ux have any thoughts?

**Comment by jwinnie** [comment]
This is a great idea, although I don’t think this is technically possible, as I think the Plank stylesheet is static and can’t be changed based on context.

**Comment by surajmandalcell** [comment]
You can set a lower opacity in your plank theme to achieve this

**Comment by Astro-City** [comment]
This would be great, but i don't think the OP example shows the issue well enough.

It's more noticeable when panel becomes dark translucent due to the wallpaper. Having the dark panel and a white dock seems inconsistent.

**Comment by cassidyjames** [comment]
The dock follows our "transient" paper-inspired UI convention of light backgrounds; see: menus, popovers, and dialogs. It's on the screen for a small amount of time to perform an action, then goes away when it's in the way (i.e. when a window is overlapping it or maximized). 

The panel, on the other hand, is always present and intended to visually fade away while always being there. So it fades into the wallpaper as best it can, or into your display bezel when your wallpaper is hidden by a maximized window.

The differences are intentional, and trying to clamor for "consistency" would actually be confusing two things that operate differently. As such, I'm going to close this as as design conflict. The difference is intentional and the request here doesn't fit with the intended design.
