### ISSUE TITLE
[$50] Remove all hex colors from widgets files [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#39]
Colors should only be defined in `gtk.css` and `gtk-dark.css`. Having them in say `gtk-widgets.css` is a major PITA for the dark stylesheet and causes duplicate code.
##

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/38405127-remove-all-hex-colors-from-widgets-files).

**Comment by h4ndshake** [comment]
Working on it. I've added a couple of rules for naming the colors (we don't want to move only Black and White to it, of course), what do you think @danrabbit 

> /*
>   Additional color definitions should be here, this will not mess our
>   stylesheets with hex codes.
> 
>   Selector rules should be transmogrified with the below rules:
>   1. Remove the "." before selector classes
>   2. Space characters between selectors will turn into a underscore (_)
>   3. Name the property inside the selector with double underscores (__)
>   4. Rules that are functions (ex: linear_gradient()) should also be declared with
>   double underscores (__)
>   5. Values inside functions should be declared with a underscore (_)
>   6. Comment what you're declaring
>   7. Add a comment with the selector after the first comment
>   8. Before your first comment, declare what stylesheet will use the selector. If
>   multiple stylesheets are using the same selector, then declare these stylesheets
>   separately (ex: apps.css, granite-wigdets.css)
> 
>   Example:
>   .greeter .button.text-button.suggested-action {} will be transmogrified to
>   greeter_button_text-button_suggested-action
> */

**Comment by danrabbit** [comment]
We don't get to change the selectors. Those are hardcoded into the toolkit

**Comment by h4ndshake** [comment]
So.. what you're asking for is to define a common pallete for all the colors? (like, idk.. material design ones) and declare it in gtk.css and gtk-dark.css?

**Comment by danrabbit** [comment]
@h4ndshake the main goal here is to reduce the size of `gtk-widgets-dark.css` and make sure the two stylesheets don't get out of sync. The dark stylesheet inherits the light stylesheet, so anywhere we can have these overrides just be setting a variable, we're potentially reducing the possibility for breakage.

An example of this is in `.window-frame` where only the first `box-shadow` is different between the stylesheets, so instead of `box-shadow: 0 0 0 1px alpha (#000, 0.75),` it should be like `box-shadow: 0 0 0 1px @window_frame_border,`. That way if we decide to change the `box-shadow` on windows some day, we don't have to change it in both stylesheets.

**Comment by grinningtadpole** [comment]
@danrabbit 

Is this issue still open? If so, I may have what you need...

I started test driving Elementary OS a week ago. The first thing I did was start working on a better dark theme -- the current one uses shades of gray that have heavy green and blue tints, which makes color sensitive work impossible. It also has bugs common to dark themes, like lightening the text shade for insensitive items, which looks fine in light themes but in dark themes makes the insensitive items look bold-faced. 

To that end, I replaced every color reference in the gtk-widgets.css with a widget/style/state specific color reference. My gtk.css and gtk-dark.css both fully encapsulate all absolute and relative colors (shades, alpha, mix, lighten, darken). I've never built a gtk theme before, and I know very little css, so this was a necessary learning tool to make it easier to experiment.

In my gtk.css, there three sections: absolute colors, relative colors, and a color map to individual widgets/styles/states. The first section defines all absolute colors (e.g., black, white, base_color, error_color). 

@define-color base_color #383e41;

Another section defines all the shades, alpha, mix, etc. 

@define-color bg_color shade (@base_color, 0.96);
@define-color bg_highlight shade (@bg_color, 1.4);
@define-color bg_highlight_alpha_04 alpha(@bg_hightlight, 0.04);

Below that, a third section maps widget-specific color entries to a relative color, as shown below:

@define-color button_box_shadow_1 @bg_highlight_alpha_04;
@define-color button_box_shadow_2 @bg_highlight_alpha_45;
@define-color button_box_shadow_3 @bg_highlight_alpha_15;
@define-color button_box_shadow_4 @bg_highlight_alpha_15;

The naming scheme here relates to the primary object in the css selector. So button_xxx, would be a color defined in the default button state, button_focus_xxx would be a color defined in the button.css, with a state of button:focus or .button:focus, etc. Therefore, each color used in the widget.css files has a one-to-one mapping here.

If two widgets/styles/states use the same color, they will get their own local reference, but map to the same relative color. The button_box_shadow_4 demonstrates this. It uses the same color as button_box_shadow_3. Rather than use the same relative color in the gtk-widget.css, I gave them each a unique color reference. That way, if you ever decide that button_box_shadow_4 should use a different color shade than 3, you don't need to modify the gtk-widget.css, only the gtk.css.

Finally, in the widget css you'll find something like this:

button,
.button,
.titlebar .stack-switcher .button.image-button {
    text-shadow: 0 1px @button_text_shadow_color;
    icon-shadow: 0 1px @button_text_shadow_color;
    background-image:
        linear-gradient(
            to bottom,
            @button_grad_start,
            @button_grad_stop_1 50%,
            @button_grad_end
            )
        );
    border: 1px solid @button_border_color;
    border-radius: 2.5px;
    box-shadow:
        inset 0 0 0 1px @button_box_shadow_1,
        inset 0 1px 0 0 @button_box_shadow_2,
        inset 0 -1px 0 0 @button_box_shadow_3,
        0 1px 0 0 @button_box_shadow_4;
    color: @button_color;
    transition: all 100ms ease-in;
}

The gtk-widget.css should never need to be edited for color information except a) if you want to add additional color stops to a gradient, or b) you need to separate two widgets/styles/states that are currently assigned the same style (e.g., you decide that ".button" and ".titlebar .stack-switcher .button.image-button" require different styles.

I found the gtk-widget.css to be a bit unwieldy when refactoring. My configuration uses the gtk-widget.css to load a bunch of smaller, individual css files from a directory named gtk-widgets. In that directory can be found base-state.css, button.css, etc. Each file corresponds to a section of the original gtk-widgets.css, and is loaded in the same order as the original gtk-widgets.css. If you need all the widgets in a single file, I would need to cat them together.

This was performed on the gtk-3.0 folder. I will be tweakiing whatever is necessary for gtk-3.22 (and eventually 3.90 or 4) as I plan to upgrade to gtk+4 (which requires 3.22, not 3.18).

I also have a different dark theme I can provide. It is a) more color neutral for those dealing with graphics  b) darker for those of us working at night, and c) fixes the incorrect shading of insensitive items.

Let me know if this is useful for you. If so, I will upload the files.

**Comment by megatux** [comment]
@grinningtadpole do you have a git repo with those changes to share?

**Comment by danrabbit** [comment]
Gonna close this because Greenfield should fix a lot of code duplication
