### ISSUE TITLE
Glitchy mouse: leaves a weird glitched square around mouse pointer

### ISSUE THREAD

**Issue by VoPusTo** [elementary/stylesheet#428]
When using Elementary OS Juno, mouse pointer (or mouse itself) is acting all weird and glitchy. I leaves a square of glitchy, frozen picture around mouse pointer all the time.

OS: Elmenetary OS 5.0 Juno 64-bit
PC: Lenovo Yoga 500-14IBD

pic1:
![20181024_161002](https://user-images.githubusercontent.com/23401484/47437529-106fb000-d7a9-11e8-8cc9-4d65440d7e91.jpg)
pic2:
![20181024_160941](https://user-images.githubusercontent.com/23401484/47437543-15ccfa80-d7a9-11e8-9af2-7855329a7a35.jpg)

Ss, for the quality, but could not PS this glitch.

**Comment by peteruithoven** [comment]
Looks like that laptop features a NVIDIA GeForce 940M? I would recommend trying another driver, switch between opensource and proprietary for example, try a newer proprietary version. 
It's unlikely this is a styling issue.

**Comment by VoPusTo** [comment]
Hi, thanks for reply.
My laptop has 940m. And you were right. It is caused by it. In Nvidia Server I set to use only Intel graphics and everything is OK. So I tried the proprietary drivers for nvidia, but it makes no difference. Also the official drivers are up to date. Is there anything else I can do about it?

**Comment by peteruithoven** [comment]
Great to hear we've narrowed down the issue. 
You could try running newer drivers from: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa
Otherwise I'd recommend doing research whether more people experience the issue, maybe also on other distro's like Ubuntu. 

We should probably close this issue, since it's not stylesheet related.
