### ISSUE TITLE
The top menu bar is messed up on Juno

### ISSUE THREAD

**Issue by DiscountGaming** [elementary/stylesheet#434]
Hello everyone,

I'm pretty sure this is a bug, but the top menu bar where all of the indicators, date & time, etc. are is shifted off the screen (see attached screenshot). 

So, please fix?

EDIT: It gets fixed when I restart the computer, but eventually appears later.
![screenshot from 2018-10-28 15-14-00](https://user-images.githubusercontent.com/44556902/47622720-89327d00-dac5-11e8-8000-d24fa3dd2c18.png)

**Comment by ryonakano** [comment]
Hi thanks for your report!
I think this issue was already reported in https://github.com/elementary/wingpanel/issues/169.

And for the future, please make sure to report your issue in an appropriate repository (in this case, https://github.com/elementary/wingpanel, because this issue is related to the top menu bar called Windpanel).
