### ISSUE TITLE
Less padding pls?

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/stylesheet#450]
I want the header bar to be A bit smaller as it looks too big for my screen(1366x768). the music app's and calendar header bar are a really big one

**Comment by rokonxr** [comment]
There should be a slim mode like Pop_OS have slim version of default themes.

**Comment by cassidyjames** [comment]
1366×768 is at the bottom of our supported resolutions. Decreasing the sizing of the entire stylesheet for this size would mean everything feeling too small at other higher resolutions and densities.

Headerbars already slim down automatic when maximizing or tiling a window, as that's a clear expression of wanting to maximize real estate. You can also try adjusting the text size in System Settings → Desktop → Appearance to give yourself a bit more room.

In the future, it might also be possible to enable non-integer scaling to set the scale below 1×, though that would likely decrease performance and introduce blurriness. But that would be out of scope of this repo.

Due to the above, I'm going to close this as a design conflict.
