### ISSUE TITLE
Ugly style

### ISSUE THREAD

**Issue by Djaler** [elementary/stylesheet#51]
Headers and toolboxs in some apps began to look so bad with last stylesheet updates.
![pasted_image_at_2017_01_10_01_44_am](https://cloud.githubusercontent.com/assets/7964583/21864467/008f76f4-d853-11e6-834f-58158dbcf26c.png)
![pasted_image_at_2017_01_10_01_45_am](https://cloud.githubusercontent.com/assets/7964583/21864435/da81daf6-d852-11e6-9451-979239ac0349.png)
![pasted_image_at_2017_01_10_01_46_am](https://cloud.githubusercontent.com/assets/7964583/21864434/da7ac888-d852-11e6-8d05-34a216e9c2d9.png)

**Comment by cassidyjames** [comment]
Thanks for the feedback, though it's a bit subjective :wink: 

The theme update prioritizes more modern apps developed and designed for the elementary (or GNOME) HIG over more legacy apps. Toolbars that are below titlebars and menubars&mdash;something that has not been recommended by the elementary or GNOME for quite some time&mdash;subsequently look a bit different now, as they match the secondary toolbar styling.

The flipside of this update is that all apps' titlebars now match, whether they're using a compact titlebar widget or the default decoration, and menubars in these legacy apps are more clearly demarcated from the titlebar and toolbars.

This was a measured decision to optimize for the future rather than keeping around special styling for legacy apps.

**Comment by danrabbit** [comment]
It's probably worth noting that this change also fixes some broken looking styles for many apps who don't use a toolbar or menu bar and rely on default decoration as the entirety of the title/tool area.

So while I don't entirely disagree that this is a less than ideal style, it's a compromise between a lot of competing concerns that (like Cassidy said) prioritizes apps designed and developed recently over legacy apps

**Comment by Djaler** [comment]
I understand that we need to move forward, but you can not abandon 90% of the applications. I am not against the use of apps designed for the elementary, but there is not to much. People have to use legacy apps.
