### ISSUE TITLE
Make the csd header of non-gtk3 maximized windows smaller

### ISSUE THREAD

**Issue by Defman21** [elementary/stylesheet#52]
I'm using the latest version of elementary theme from git and I've noticed that when i maximize a gtk3 window, it's headerbar gets a bit smaller (reducing inner padding). Is it possible to make non-gtk3 headerbars/titlebars do the same?

**Comment by danrabbit** [comment]
It's already as small as it can get for `titlebar.compact` and `titlebar.default-decoration` to be the same height. I'd love to make it a couple pixels smaller, but I can't :/

**Comment by Defman21** [comment]
Hmm yeah. I've compared a non-maximized gtk3 headerbar and it's a bit bigger than the decoration of non-gtk3 windows, but once I maximize a gtk3 window, its headerbar height is the same as the height of any other non-gtk3 window.

**Comment by danrabbit** [comment]
There's a `.compact` class in the stylesheet if developers choose to reduce the size of their headerbar. However the default size of the `titlebar` element (Gtk.Headerbar) does have a little more padding and that won't change. It's not possible to enforce the same absolute size for headerbars since they can contain any number of widgets and must accommodate the height of those widgets.

**Comment by Defman21** [comment]
Got it, thanks :)
