### ISSUE TITLE
Menus glitch on borders

### ISSUE THREAD

**Issue by pmbernardino** [elementary/stylesheet#525]
Posted [here](https://elementaryos.stackexchange.com/questions/19307/drop-down-menus-in-some-applications-have-visual-problems) the issue that I have on my install on a HP Compaq dc7800p small factor. And some one told me to ask for help here.
![Captura de ecrã de 2019-07-05 22 04 01](https://user-images.githubusercontent.com/52718547/60918160-86aa3900-a28a-11e9-9708-983962bfcedd.png)
![Captura de ecrã de 2019-07-05 21-58-51](https://user-images.githubusercontent.com/52718547/60918191-9a559f80-a28a-11e9-8ece-6f3699332e35.png)
![Captura de ecrã de 2019-07-06 09-35-40](https://user-images.githubusercontent.com/52718547/60918196-9cb7f980-a28a-11e9-8e64-4e458bdc9324.png)
Help plz

Pedro Bernardino

**Comment by danrabbit** [comment]
Hey thanks for filing an issue report. Unfortunately, there's nothing I can do about this from within the stylesheet. My guess is that this is either an issue in LibreOffice's Gtk emulation or a driver issue.

Closing as "Out of Scope" since the stylesheet is not in charge of rendering in LibreOffice and I'm unable to do anything to resolve this issue
