### ISSUE TITLE
month display problems on Elementary OS 5.0

### ISSUE THREAD

**Issue by KoZZerog** [elementary/stylesheet#527]
![Снимок экрана от 2019-07-13 23 16 09](https://user-images.githubusercontent.com/52867353/61176150-3bfb2a80-a5c4-11e9-8544-12296863512e.png)

On russian "Июль", not "июл"

**Comment by TeslaSesla** [comment]
Если Я не ошибаюсь, то для всех месяцев используется сокращение из 3-х букв

**Comment by jlnr** [comment]
This issue should be moved to wingpanel-indicator-datetime.

Google Translate says this issue is about not using 3-letter abbreviations for the month in Wingpanel. I've asked #ru in the internationalization Slack to look at this, as it can be fixed in the string files through Weblate.

It seems that the English translation started the trend of using a two-letter weekday, and a three-letter month. I think it looks strange in German as well, there's so much space and yet it uses cryptic abbreviations.

**Comment by peteruithoven** [comment]
I think this is actually a Granite issue.

The indicated uses Granite:
https://github.com/elementary/wingpanel-indicator-datetime/blob/8f2d42aed586974f79b47c611cee8f5d31817ad7/src/Widgets/PanelLabel.vala#L59-L71

Function in Granite:
https://github.com/elementary/granite/blob/0975372243d0a88ec16d4abc42ab226aa41484d2/lib/DateTime.vala#L145-L173

**Comment by peteruithoven** [comment]
I don't see the months translated in: https://github.com/elementary/granite/blob/master/po/ru.po
As mentions there GLib.DateTime format is used to show the date:
https://valadoc.org/glib-2.0/GLib.DateTime.format.html

Not sure where the translations are in that case.

**Comment by danrabbit** [comment]
These strings come from GLib. Closing as this cannot be fixed in the stylesheet. Please submit translation corrections to GLib here: https://gitlab.gnome.org/GNOME/glib/blob/master/po/ru.po
