### ISSUE TITLE
Rewrite in Sass

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#532]
Some of these selectors are really hard to keep track of in regular CSS

**Comment by kgrubb** [comment]
here's some reasons on why we'd want to move to the sass-based stylesheet paradigm:

* A Sass build system eases creation of theme variants

* Possibly increases performance due to precompiled variables

* Shrinks filesize via compressing/minifying the gtk.css file(s)

* Makes public & private variables more straightforward, better defining the stylesheet's api

* Simplifies dealing with widget trees

**Comment by danrabbit** [comment]
I'm gonna close this since it's happening and I'm not sure what more there is to track here
