### ISSUE TITLE
Calculator icon disappeared

### ISSUE THREAD

**Issue by ovishchuk** [elementary/stylesheet#564]
Calculator icon has disappeared since the last update. Although the application is running fine.
![Знімок з 2019-11-23 11-33-27](https://user-images.githubusercontent.com/42047832/69476706-fc501500-0de5-11ea-9d00-b09642d3a538.png)
![Знімок з 2019-11-23 11-33-42](https://user-images.githubusercontent.com/42047832/69476707-feb26f00-0de5-11ea-90de-4e6625859b0a.png)
![Знімок з 2019-11-23 11-36-00](https://user-images.githubusercontent.com/42047832/69476708-02de8c80-0de6-11ea-898a-49704ece7a36.png)

**Comment by ryonakano** [comment]
Hi @ovishchuk, what is your system language?

**Comment by ovishchuk** [comment]
> Hi @ovishchuk, what is your system language?

Hi @ryonakano, it is Ukrainian.

**Comment by ovishchuk** [comment]
@ryonakano, I just tried English and icon appeared. It does not seem to work for Ukrainian (Cyrillic).

**Comment by ryonakano** [comment]
@ovishchuk Thanks! I guess this issue is because the icon name of Calculator was translated by mistake. Here represents the icon name and it shouldn't be translated, but actually translated:

https://github.com/elementary/calculator/blob/da95868f7e9c638c4ded528208bf374fdba7b9df/po/extra/uk.po#L70-L71

**Comment by danrabbit** [comment]
An update for calculator has been released. It should be available soon :)
