### ISSUE TITLE
Draw selection around image radiobuttons

### ISSUE THREAD

**Issue by danrabbit** [elementary/stylesheet#575]
```
radiobutton.image-button {
    border: 1px solid transparent;
    border-radius: 3px;
    padding: 6px;
}

radiobutton.image-button:checked:not(:backdrop) {
    background-color: alpha (@colorAccent, 0.1);
    border-color: @colorAccent;
    color: @BLUEBERRY_500;
}

radiobutton.image-button:checked:not(:backdrop) image {
    color: @BLUEBERRY_500;
}

radiobutton.image-button:checked:backdrop {
    background-color: alpha (@text_color, 0.1);
    border-color: alpha (@text_color, 0.6);
}
```

Looks like:

![Screenshot from 2020-01-10 10 00 13@2x](https://user-images.githubusercontent.com/7277719/72175225-7df90380-3390-11ea-98d0-0685d2aeb1a6.png)
![Screenshot from 2020-01-10 10 00 23@2x](https://user-images.githubusercontent.com/7277719/72175227-7e919a00-3390-11ea-9e58-4e9ccedfb587.png)
![Screenshot from 2020-01-10 10 02 09@2x](https://user-images.githubusercontent.com/7277719/72175228-7e919a00-3390-11ea-8cda-89f223d6e183.png)

**Comment by Member1221** [comment]
An extra option would be to potentially place the radio button underneath the element?

**Comment by GammaGames** [comment]
I think this is an interesting design and have been using it in my own projects for a little over a year. I've found a couple places I prefer to use it over a traditional radio input:
* Small lists of short text options
* Image/icon choices
* Interfaces where touch screen interactions are a target
* Nested choices

It definitely takes more space than a regular radio menu, but I've found it easier for users that are using a touch screen or are used to normally using one. I hide the radio select as well, since the highlight accent already shows what is selected. I also found it makes navigating nested lists easier when you need to swap categories, and I prefer being able to see how each item creates your options as you select a parent value. It looks better with animations, but for a basic prototype the following works fine IMO:

![Screen record from 2020-01-27 12 21 51](https://user-images.githubusercontent.com/7832163/73206347-f9ccad00-40ff-11ea-830e-169c0bdb9004.gif)
