### ISSUE TITLE
There should be a slim mode like Pop_OS have slim version of default themes.

### ISSUE THREAD

**Issue by rokonxr** [elementary/stylesheet#619]
There should be a slim mode like Pop_OS have slim version of default themes that have less padding in some areas like Headerbar etc...
This feature will be really helpful for low resolution monitors.

_Originally posted by @rokonxr in https://github.com/elementary/stylesheet/issues/450#issuecomment-621129603_

**Comment by cassidyjames** [comment]
The default Pop!_OS style is based on Adwaita, and thus has a lot of padding everywhere—much, much more than the elementary stylesheet. The slim mode was introduced to give an option to counteract that, but ends up being closer to elementary OS in its sizing/padding.

Headerbars currently slim down when windows are maximized or tiled, because the user has expressed a want to maximize the real estate. But introducing an entire slimmer variant of the stylesheet would also mean nearly twice as much maintenance work to ensure everything always looks great, and would increase the load on our third-party app developer ecosystem.

Considering all of the above, I'm going to close this as a design conflict as it is not in line with our design goals.
