### ISSUE TITLE
Thinner Title Bars.

### ISSUE THREAD

**Issue by spirulin** [elementary/stylesheet#699]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Bars are too big and take too much space, and they make the UI look uglier. Thinner title bars like in this video: https://www.youtube.com/watch?v=9CZiUcxt614

**Describe the solution you'd like**
Thinner title bars look stunning in this video. The UI looks so much nicer. And gives more space which is always a good thing.

**Existing work**
It can be achieved with some tweaking but for most people, it's too much work.

**Describe alternatives you've considered**
Option in the Settings to make them thinner.

**Additional context**
https://www.youtube.com/watch?v=9CZiUcxt614

**Comment by cassidyjames** [comment]
The headerbars in that video look comically squished to me, with little-to-no whitespace. It's already up to apps to determine what widgets they pack into the headerbar, and apps like Terminal do use a more compact style. Perhaps we could make the calculator use a slimmer titlebar like Terminal, but that would be out of scope of the stylesheet.

I'm inclined to close this as out of scope in general since this is mostly up to apps, but feel free to clarify if I'm wrong. :P

**Comment by danrabbit** [comment]
This seems to be exacerbated by the low resolution of this particular display as well. I think the text-sized-based layout scaling work we’re doing in Greenfield should largely alleviate these concerns for users with low display resolutions
