### ISSUE TITLE
Wish: Toggle / Switch for window minimize button in settings

### ISSUE THREAD

**Issue by Hacime** [elementary/stylesheet#846]
- [x]  I have searched open and closed issues for duplicates.

Wish: An out of the box toogle / switch in the settings to add a minimize button to the windows would be great.
Users could choose to use this function in eOS if they prefer a minimize button. (Instead of using tweaks to add it.)

It's okay if there are reasons not to implement this.
Thanks for eOS, I think it's really good!

**Comment by hanaral** [comment]
The reason for the lack of the minimise is because the desktop is designed specifically for managing windows with workspaces. If an app needs to be running in the background, it should actually be in the background.
If you find it difficult to get used to the workspaces, changing the workspaces keybinds is what helped *me*
Also this is the stylesheet page, it should be under Gala’s one.

**Comment by btkostner** [comment]
Most of these issues are tracked [on the OS repo](https://github.com/elementary/os/issues?q=minimize), that's why your search came up empty in this repository. I would take a look at some of those issues to understand the reasoning behind it. At this time, we have no intention of adding a minimize button.
