### ISSUE TITLE
Strange Headerbar Size

### ISSUE THREAD

**Issue by umahdroid** [elementary/stylesheet#977]
## What Happened

Different headerbar size in stock apps

## Expected Behavior

Headerbar size should be have same size

## Steps to Reproduce

1. Open different apps
2. Compare the headerbar size

![g2492](https://user-images.githubusercontent.com/39919860/111773860-a048b400-88a6-11eb-8b85-841890f28e44.png)

## Platform Information

DISTRIB_ID=elementary
DISTRIB_RELEASE=6
DISTRIB_CODENAME=odin
DISTRIB_DESCRIPTION="elementary OS 6 Early Access"

**Comment by cassidyjames** [comment]
Headerbars intentionally size to match their contents. In this case, you have a GNOME app that does its own styling, an app with an intentionally-slim headerbar, AppCenter which in this case might have custom styling that is changing its headerbar size, but the rest are slightly different sizes due to different widgets being packed inside.

I'm not sure if there's anything actionable here for us, as GTK widgets expand to match their contents. This is more a HIG question, honestly. It's possible there might be some special handling of margins in headerbars we could try to enforce in the stylesheet, which might resolve part of this issue, but I'm not really sure if that's what we want to do.

**Comment by danrabbit** [comment]
Yeah the only thing we could do is set a large min-height which would make sure that apps take up more space even when they don't need it. I think the space savings is more of a benefit than anything lost by headerbars being slightly different heights in different apps

Closing as "Design conflict"
