### ISSUE TITLE
CSS classes for accent colors

### ISSUE THREAD

**Issue by JeysonFlores** [elementary/stylesheet#984]
## Problem

As a begginer eOS app dev one thing I realize when I was doing some sketches is: **_How can I implement colors on eOS apps in a smart and integrated way?_**

## Proposal

Since eOS 6 will have accent colors I think it would be nice to have some CSS classes that could make reference to the actual accent color of the user. Example:

```css
.accent-color-100

.accent-color-300

.accent-color-500

.accent-color-700

.accent-color-900

```
Doing that, if the developer wants to implement color on an app he / she could use one of the tones of the actual accent color, **avoiding sacrifice the integration for the customization**. One example of this problem could be Byte (with its colored headerbar) or Eddy (also having a colored headerbar) but there are more examples of this.
## Prior Art

Here's an example of **Planner** using the equivalent of _.accent-color-100_ and _.accent-color-300_ for its left panel. I modified its CSS using GTK_DEBUG=interactive.
> Banana
 ![screenshot](https://preview.redd.it/ryg92guvs8r61.png?width=1026&format=png&auto=webp&s=f5824bda9c70abfb6bad4876b706a767e298e8ba)
 > Grape
 ![screenshot](https://preview.redd.it/2xvg6ouvs8r61.png?width=1026&format=png&auto=webp&s=7a4e9ea846f25972208c5f74916535996e4526fb)
> Lime
 ![screenshot](https://preview.redd.it/1zgaoluvs8r61.png?width=1026&format=png&auto=webp&s=33c2ea259617d9bd690edabefcce43a6bc6d3449)

## Notes
- The examples are examples of modifying the _background-color_ property in CSS however a class for changing also the _color_ property for color text would be nice.
- I hope you guys read it and understand it. I'm sure you can implement it better than I think if you decide to. 

# Thanks for reading.

**Comment by cassidyjames** [comment]
The problem is we can't predict how apps will want to use accent colors, and it's difficult to ensure we're not setting too vague or specific of properties on those classes; we can set the background-color, but what if they actually wanted a gradient, not a solid color? What about borders, focus states, and yeah, foreground colors?

I think sticking to the defined and exported GTK CSS variables is ideal here, as it takes very little CSS for a developer to determine how and where exactly they want to use the colors.

https://github.com/elementary/stylesheet/blob/3047efbfabe723e0b0f2b8ee3d53bed528be4b14/src/variants/banana.scss#L22-L29

**Comment by danrabbit** [comment]
For this specific use case, I would use custom CSS and the variables `@theme_selected_bg_color` and `@theme_selected_fg_color`. These values have been contrast checked and there are accompanying values: `@theme_unfocused_selected` and `@theme_unfocused_selected_fg_color`

**Comment by JeysonFlores** [comment]
I see, thanks for reading!
