### ISSUE TITLE
Filezilla swtiches to XP Style theme

### ISSUE THREAD

**Issue by KorbsStudio** [elementary/stylesheet#991]
## What Happened
When using Filezilla, I noticed it's user interface's theme has changed to a XP like theme while elementary's stylesheet is enabled. 

## Platform Information
Tested on elementary OS 6 (VM) and elementary OS 5.1.7

[Video Preview](https://i.imgur.com/fEEGjZh.mp4)

**Comment by danrabbit** [comment]
Looks like FileZilla is using Gtk2. This is no longer supported

Closing as "out of scope" since gtk2 styles are no longer supported. FileZilla needs to update

**Comment by cassidyjames** [comment]
If this is thee Flatpak version, it's more precisely because it's falling back to Adwaita in the container (since the new elementary stylesheet doesn't exist on the Flathub remote). On elementary OS 5, you can install the Flatpak and it automatically installs `org.gtk.Gtk3theme.elementary`, and then Filezilla correctly uses the GTK3 stylesheet.

Regardless, there's nothing about the stylesheet itself that controls this, and it is behaving like every other Flatpak app not designed for elementary OS.

**Comment by KorbsStudio** [comment]
I went ahead install the Flatpak version and did fallback to GTK3 theme with no problems.
Although, it's quite blinding since it won't use a dark mode.
